/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import bd.Conexion;
import Controlador.PersistenciaFactura;
import Modelo.Factura;
import javax.swing.*;
import com.sun.istack.internal.logging.Logger;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MostrarFactura extends javax.swing.JFrame {

    /**
     * Creates new form MostrarFactura
     */
    public MostrarFactura() {
        initComponents();
        mostrarDatos("");
        jTablaFactura.setModel(new DefaultTableModel());
    }
         void mostrarDatos(String numero){
         Conexion conexionOracle = new Conexion();
         DefaultTableModel modelo= new DefaultTableModel();
         modelo.addColumn("NRO_FACTURA");
         modelo.addColumn("RUT_CLIENTE");
         modelo.addColumn("Fecha2");
         modelo.addColumn("MONTO");
         modelo.addColumn("fecha3");
         jTablaFactura.setModel(modelo);
         String sql="";
         if(numero.equals("")){
             sql = "Select * from factura";
         }
         else{
             sql = "Select * from factura where nro_factura = '"+numero+"'";
         } 
         String[] datos = new String[5];
         try{
         conexionOracle.conectar();
         Connection conexion = conexionOracle.getConnection();
         PreparedStatement buscar = conexion.prepareStatement(sql);
         ResultSet rs = buscar.executeQuery();
         while(rs.next()){
             datos[0]=rs.getString(1);
             datos[1]=rs.getString(2);
             datos[2]=rs.getString(3);
             datos[3]=rs.getString(4);
             datos[4]=rs.getString(5);
             modelo.addRow(datos);
             
         }
         }catch(SQLException ex){
             System.out.println("Error");
             //Logger.getLogger(MuestraFactura.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaFactura = new javax.swing.JTable();
        txtCodigoFactura = new javax.swing.JTextField();
        btnModificarFactura = new javax.swing.JButton();
        btnAgregarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnListarFactura.setText("Listar");
        btnListarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFacturaActionPerformed(evt);
            }
        });

        jTablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro_factura", "Rut_cliente", "Fecha2", "Monto", "Fecha3"
            }
        ));
        jScrollPane2.setViewportView(jTablaFactura);

        btnModificarFactura.setText("Modificar Factura");
        btnModificarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFacturaActionPerformed(evt);
            }
        });

        btnAgregarFactura.setText("Agregar Factura");
        btnAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarFactura)
                        .addGap(43, 43, 43)
                        .addComponent(txtCodigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnModificarFactura)
                            .addComponent(btnAgregarFactura))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnListarFactura)
                        .addComponent(txtCodigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModificarFactura)
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarFactura)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFacturaActionPerformed
        
        mostrarDatos(txtCodigoFactura.getText());
    }//GEN-LAST:event_btnListarFacturaActionPerformed

    private void btnModificarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFacturaActionPerformed
        //        Vista.MostrarFactura ini= new Vista.MostrarFactura();
        //        ini.setVisible(true);
        //        Vista.ModificarFactura oModificarF=new Vista.ModificarFactura();
        //        oModificarF.setVisible(false);
        //        dispose();

        javax.swing.JFrame omf= new ModificarFactura();
        MostrarFactura objetomf=new MostrarFactura();
        omf.setSize(objetomf.getSize());
        omf.show();
    }//GEN-LAST:event_btnModificarFacturaActionPerformed

    private void btnAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFacturaActionPerformed
        javax.swing.JFrame objetomf= new AgregarFactura();
        MostrarFactura objeto1mf=new MostrarFactura();
        objetomf.setSize(objeto1mf.getSize());
        objetomf.show();
    }//GEN-LAST:event_btnAgregarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JButton btnListarFactura;
    private javax.swing.JButton btnModificarFactura;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaFactura;
    private javax.swing.JTextField txtCodigoFactura;
    // End of variables declaration//GEN-END:variables
}
