/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Operacion.Agregar;

import Modelo.Alcohol;
import static ventas.Ventas.arrayAlcohol;

/**
 *
 * @author Duoc
 */
public class OpAgAlcohol extends javax.swing.JPanel {

    /**
     * Creates new form OpAgAlcohol
     */
    public OpAgAlcohol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        txtDistribucion = new javax.swing.JTextField();
        txtGradoAlcohol = new javax.swing.JTextField();
        btnGuardarAlcohol = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblTextoInicioAlcohol = new javax.swing.JLabel();
        lblDescProductos = new javax.swing.JLabel();
        lblValProducto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblDistribucion = new javax.swing.JLabel();
        lblGradoAlcohol = new javax.swing.JLabel();
        txtDescProductos = new javax.swing.JTextField();
        txtValProducto = new javax.swing.JTextField();
        btnGuardarAlcohol1 = new javax.swing.JButton();

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnGuardarAlcohol.setText("Guardar");
        btnGuardarAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlcoholActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblTextoInicioAlcohol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextoInicioAlcohol.setText("Agregar Alcohol");

        lblDescProductos.setText("Descripción Productos");

        lblValProducto.setText("Valor Productos");

        lblCantidad.setText("Cantidad Producto");

        lblDistribucion.setText("Distribuciòn");

        lblGradoAlcohol.setText("Grado de Alcohol");

        txtDescProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescProductosKeyTyped(evt);
            }
        });

        txtValProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValProductoActionPerformed(evt);
            }
        });

        btnGuardarAlcohol1.setText("Validar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTextoInicioAlcohol)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescProductos)
                            .addComponent(lblValProducto)
                            .addComponent(lblCantidad)
                            .addComponent(lblDistribucion)
                            .addComponent(lblGradoAlcohol))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtValProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGradoAlcohol)
                            .addComponent(txtDistribucion)
                            .addComponent(txtDescProductos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver)
                            .addComponent(btnGuardarAlcohol)
                            .addComponent(btnGuardarAlcohol1))
                        .addGap(94, 94, 94)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTextoInicioAlcohol)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescProductos)
                            .addComponent(txtDescProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarAlcohol1)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValProducto)
                    .addComponent(txtValProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAlcohol))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDistribucion)
                    .addComponent(txtDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnVolver)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradoAlcohol)
                    .addComponent(txtGradoAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnGuardarAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlcoholActionPerformed
        boolean validarDatos = Controller.AlcoholController.validarDatos(
                txtDescProductos,
                txtCantidad,
                txtValProducto,
                txtDistribucion,
                txtGradoAlcohol
        );

        if (validarDatos) {
            System.out.println("Se puede guardar");
            Alcohol objAlcohol = new Alcohol(txtDescProductos.getText(), Integer.parseInt(txtValProducto.getText()), Integer.parseInt(txtCantidad.getText()), txtDistribucion.getText(), Double.parseDouble(txtGradoAlcohol.getText()));
            arrayAlcohol.add(objAlcohol);
        } else {
            System.out.println("NO se puede guardar");
        }

    }//GEN-LAST:event_btnGuardarAlcoholActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed


    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtValProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValProductoActionPerformed

    }//GEN-LAST:event_txtValProductoActionPerformed

    private void txtDescProductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescProductosKeyTyped

    }//GEN-LAST:event_txtDescProductosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAlcohol;
    private javax.swing.JButton btnGuardarAlcohol1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescProductos;
    private javax.swing.JLabel lblDistribucion;
    private javax.swing.JLabel lblGradoAlcohol;
    private javax.swing.JLabel lblTextoInicioAlcohol;
    private javax.swing.JLabel lblValProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescProductos;
    private javax.swing.JTextField txtDistribucion;
    private javax.swing.JTextField txtGradoAlcohol;
    private javax.swing.JTextField txtValProducto;
    // End of variables declaration//GEN-END:variables
}
