/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Operacion.Agregar;
//import  ventas.Ventas.*;
import Modelo.Cigarros;
import static ventas.Ventas.arrayCigarros;
/**
 *
 * @author Duoc
 */
public class OpAgCigarros extends javax.swing.JPanel {

    /**
     * Creates new form Ingresar
     */
    public OpAgCigarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDescProductos = new javax.swing.JLabel();
        lblValProducto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblDistribucion = new javax.swing.JLabel();
        lblCantidadNicotina = new javax.swing.JLabel();
        lblTipoFiltro = new javax.swing.JLabel();
        txtDescProductos = new javax.swing.JTextField();
        txtValProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDistribucion = new javax.swing.JTextField();
        txtCantidadNicotina = new javax.swing.JTextField();
        txtTipoFiltro = new javax.swing.JTextField();
        btnGuardarCigarros = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar Cigarros");

        lblDescProductos.setText("Descripciòn Productos");

        lblValProducto.setText("Valor Productos");

        lblCantidad.setText("Cantidad Producto");

        lblDistribucion.setText("Distribuciòn");

        lblCantidadNicotina.setText("Cantidad Nicotina");

        lblTipoFiltro.setText("Tipo Filtro");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnGuardarCigarros.setText("Guardar");
        btnGuardarCigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCigarrosActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescProductos)
                            .addComponent(lblValProducto)
                            .addComponent(lblCantidad)
                            .addComponent(lblDistribucion)
                            .addComponent(lblCantidadNicotina)
                            .addComponent(lblTipoFiltro))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValProducto)
                                .addComponent(txtTipoFiltro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(txtCantidadNicotina, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDistribucion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDescProductos, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver)
                            .addComponent(btnGuardarCigarros))
                        .addGap(94, 94, 94)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescProductos)
                    .addComponent(txtDescProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValProducto)
                    .addComponent(txtValProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCigarros))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDistribucion)
                    .addComponent(txtDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnVolver)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadNicotina)
                    .addComponent(txtCantidadNicotina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoFiltro)
                    .addComponent(txtTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnGuardarCigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCigarrosActionPerformed
        //(String descProductos, int valProducto, int cantidad, String distribucion, int cantidadNicotina, String tipoFiltro)
        Cigarros objCigarros = new Cigarros(txtDescProductos.getText(), Integer.parseInt(txtValProducto.getText()), Integer.parseInt(txtCantidad.getText()), txtDistribucion.getText(), Integer.parseInt(txtCantidadNicotina.getText()), txtTipoFiltro.getText());
        arrayCigarros.add(objCigarros); 
         
    }//GEN-LAST:event_btnGuardarCigarrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCigarros;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidadNicotina;
    private javax.swing.JLabel lblDescProductos;
    private javax.swing.JLabel lblDistribucion;
    private javax.swing.JLabel lblTipoFiltro;
    private javax.swing.JLabel lblValProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadNicotina;
    private javax.swing.JTextField txtDescProductos;
    private javax.swing.JTextField txtDistribucion;
    private javax.swing.JTextField txtTipoFiltro;
    private javax.swing.JTextField txtValProducto;
    // End of variables declaration//GEN-END:variables
}
