/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

/**
 *
 * @author Duoc
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmensajebienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itemOpcigarros = new javax.swing.JMenuItem();
        itemOpagnarcoticos = new javax.swing.JMenuItem();
        itemOpagpasajes = new javax.swing.JMenuItem();
        itemOpagagalcohol = new javax.swing.JMenuItem();
        itemOpAgMedicamentos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemopelcigarros = new javax.swing.JMenuItem();
        itemopelnarcoticos = new javax.swing.JMenuItem();
        itemopelpasajes = new javax.swing.JMenuItem();
        itemopelalcohol = new javax.swing.JMenuItem();
        itemopelmedicamentos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemopedcigarros = new javax.swing.JMenuItem();
        itemopednarcoticos = new javax.swing.JMenuItem();
        itemopedpasajes = new javax.swing.JMenuItem();
        itemopedalcohol = new javax.swing.JMenuItem();
        itemopedmedicamentos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        itemmacigarros = new javax.swing.JMenuItem();
        itemmaagnarcoticos = new javax.swing.JMenuItem();
        itemmaagpasajes = new javax.swing.JMenuItem();
        itemmaagagalcohol = new javax.swing.JMenuItem();
        itemmaAgMedicamentos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        itemmaelcigarros = new javax.swing.JMenuItem();
        itemmaelnarcoticos = new javax.swing.JMenuItem();
        itemmaelpasajes = new javax.swing.JMenuItem();
        itemmaelalcohol = new javax.swing.JMenuItem();
        itemmaelmedicamentos = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itemmaedcigarros = new javax.swing.JMenuItem();
        itemmaednarcoticos = new javax.swing.JMenuItem();
        itemmaedpasajes = new javax.swing.JMenuItem();
        itemmaedalcohol = new javax.swing.JMenuItem();
        itemmedmedicamentos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblmensajebienvenida.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblmensajebienvenida.setText("BIENVENIDO A SISTEMA VIEJA CTM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/wb.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("Operación");

        jMenu4.setText("Agregar");

        itemOpcigarros.setText("Cigarros");
        itemOpcigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpcigarrosActionPerformed(evt);
            }
        });
        jMenu4.add(itemOpcigarros);

        itemOpagnarcoticos.setText("Narcoticos");
        itemOpagnarcoticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpagnarcoticosActionPerformed(evt);
            }
        });
        jMenu4.add(itemOpagnarcoticos);

        itemOpagpasajes.setText("Pasajes");
        jMenu4.add(itemOpagpasajes);

        itemOpagagalcohol.setText("Alcohol");
        jMenu4.add(itemOpagagalcohol);

        itemOpAgMedicamentos.setText("Medicamentos");
        jMenu4.add(itemOpAgMedicamentos);

        jMenu1.add(jMenu4);

        jMenu5.setText("Eliminar");

        itemopelcigarros.setText("Cigarros");
        jMenu5.add(itemopelcigarros);

        itemopelnarcoticos.setText("Narcoticos");
        jMenu5.add(itemopelnarcoticos);

        itemopelpasajes.setText("Pasajes");
        jMenu5.add(itemopelpasajes);

        itemopelalcohol.setText("Alcohol");
        itemopelalcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemopelalcoholActionPerformed(evt);
            }
        });
        jMenu5.add(itemopelalcohol);

        itemopelmedicamentos.setText("Medicamentos");
        jMenu5.add(itemopelmedicamentos);

        jMenu1.add(jMenu5);

        jMenu6.setText("Editar");

        itemopedcigarros.setText("Cigarros");
        jMenu6.add(itemopedcigarros);

        itemopednarcoticos.setText("Narcoticos");
        jMenu6.add(itemopednarcoticos);

        itemopedpasajes.setText("Pasajes");
        jMenu6.add(itemopedpasajes);

        itemopedalcohol.setText("Alcohol");
        jMenu6.add(itemopedalcohol);

        itemopedmedicamentos.setText("Medicamentos");
        jMenu6.add(itemopedmedicamentos);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenedores");

        jMenu7.setText("Agregar");

        itemmacigarros.setText("Cigarros");
        itemmacigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmacigarrosActionPerformed(evt);
            }
        });
        jMenu7.add(itemmacigarros);

        itemmaagnarcoticos.setText("Narcoticos");
        itemmaagnarcoticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmaagnarcoticosActionPerformed(evt);
            }
        });
        jMenu7.add(itemmaagnarcoticos);

        itemmaagpasajes.setText("Pasajes");
        jMenu7.add(itemmaagpasajes);

        itemmaagagalcohol.setText("Alcohol");
        jMenu7.add(itemmaagagalcohol);

        itemmaAgMedicamentos.setText("Medicamentos");
        jMenu7.add(itemmaAgMedicamentos);

        jMenu2.add(jMenu7);

        jMenu8.setText("Eliminar");

        itemmaelcigarros.setText("Cigarros");
        jMenu8.add(itemmaelcigarros);

        itemmaelnarcoticos.setText("Narcoticos");
        jMenu8.add(itemmaelnarcoticos);

        itemmaelpasajes.setText("Pasajes");
        jMenu8.add(itemmaelpasajes);

        itemmaelalcohol.setText("Alcohol");
        itemmaelalcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmaelalcoholActionPerformed(evt);
            }
        });
        jMenu8.add(itemmaelalcohol);

        itemmaelmedicamentos.setText("Medicamentos");
        jMenu8.add(itemmaelmedicamentos);

        jMenu2.add(jMenu8);

        jMenu9.setText("Editar");

        itemmaedcigarros.setText("Cigarros");
        jMenu9.add(itemmaedcigarros);

        itemmaednarcoticos.setText("Narcoticos");
        jMenu9.add(itemmaednarcoticos);

        itemmaedpasajes.setText("Pasajes");
        jMenu9.add(itemmaedpasajes);

        itemmaedalcohol.setText("Alcohol");
        jMenu9.add(itemmaedalcohol);

        itemmedmedicamentos.setText("Medicamentos");
        jMenu9.add(itemmedmedicamentos);

        jMenu2.add(jMenu9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        jMenuItem1.setText("Reporte1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblmensajebienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmensajebienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemOpcigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpcigarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemOpcigarrosActionPerformed

    private void itemOpagnarcoticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpagnarcoticosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemOpagnarcoticosActionPerformed

    private void itemopelalcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemopelalcoholActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemopelalcoholActionPerformed

    private void itemmacigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmacigarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemmacigarrosActionPerformed

    private void itemmaagnarcoticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmaagnarcoticosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemmaagnarcoticosActionPerformed

    private void itemmaelalcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmaelalcoholActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemmaelalcoholActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemOpAgMedicamentos;
    private javax.swing.JMenuItem itemOpagagalcohol;
    private javax.swing.JMenuItem itemOpagnarcoticos;
    private javax.swing.JMenuItem itemOpagpasajes;
    private javax.swing.JMenuItem itemOpcigarros;
    private javax.swing.JMenuItem itemmaAgMedicamentos;
    private javax.swing.JMenuItem itemmaagagalcohol;
    private javax.swing.JMenuItem itemmaagnarcoticos;
    private javax.swing.JMenuItem itemmaagpasajes;
    private javax.swing.JMenuItem itemmacigarros;
    private javax.swing.JMenuItem itemmaedalcohol;
    private javax.swing.JMenuItem itemmaedcigarros;
    private javax.swing.JMenuItem itemmaednarcoticos;
    private javax.swing.JMenuItem itemmaedpasajes;
    private javax.swing.JMenuItem itemmaelalcohol;
    private javax.swing.JMenuItem itemmaelcigarros;
    private javax.swing.JMenuItem itemmaelmedicamentos;
    private javax.swing.JMenuItem itemmaelnarcoticos;
    private javax.swing.JMenuItem itemmaelpasajes;
    private javax.swing.JMenuItem itemmedmedicamentos;
    private javax.swing.JMenuItem itemopedalcohol;
    private javax.swing.JMenuItem itemopedcigarros;
    private javax.swing.JMenuItem itemopedmedicamentos;
    private javax.swing.JMenuItem itemopednarcoticos;
    private javax.swing.JMenuItem itemopedpasajes;
    private javax.swing.JMenuItem itemopelalcohol;
    private javax.swing.JMenuItem itemopelcigarros;
    private javax.swing.JMenuItem itemopelmedicamentos;
    private javax.swing.JMenuItem itemopelnarcoticos;
    private javax.swing.JMenuItem itemopelpasajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblmensajebienvenida;
    // End of variables declaration//GEN-END:variables
}
