/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Operacion.Agregar.OpAgCigarros;
import Vista.Operacion.Agregar.OpAgAlcohol;
import Vista.Operacion.Eliminar.*;
import Vista.Operacion.Editar.*;

/**
 *
 * @author Duoc
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnInicio = new javax.swing.JPanel();
        lblTextoBienvenida = new javax.swing.JLabel();
        lblImagenAbuelita = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        itmOperacion = new javax.swing.JMenu();
        itmOpAgregar = new javax.swing.JMenu();
        itmOpAgCigarros = new javax.swing.JMenuItem();
        itmOpAgNarcoticos = new javax.swing.JMenuItem();
        itmOpAgPasajes = new javax.swing.JMenuItem();
        itmOpAgAlcohol = new javax.swing.JMenuItem();
        itmOpAgMedicamentos = new javax.swing.JMenuItem();
        itmOpEliminar = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        itmOpElNarcoticos = new javax.swing.JMenuItem();
        itmOpElPasajes = new javax.swing.JMenuItem();
        itmOpElAlcohol = new javax.swing.JMenuItem();
        itmOpElMedicamentos = new javax.swing.JMenuItem();
        itmOpEditar = new javax.swing.JMenu();
        itmOpEdCigarros = new javax.swing.JMenuItem();
        itmOpEdNarcoticos = new javax.swing.JMenuItem();
        itmOpEdPasajes = new javax.swing.JMenuItem();
        itmOpEdAlcohol = new javax.swing.JMenuItem();
        itmOpEdMedicamentos = new javax.swing.JMenuItem();
        itmMantenedores = new javax.swing.JMenu();
        itmManCigarros = new javax.swing.JMenuItem();
        itmManNarcoticos = new javax.swing.JMenuItem();
        itmManPasajes = new javax.swing.JMenuItem();
        itmManAlcohol = new javax.swing.JMenuItem();
        itmManMedicamentos = new javax.swing.JMenuItem();
        itmReportes = new javax.swing.JMenu();
        itmRepCigarros = new javax.swing.JMenuItem();
        itmRepNarcoticos = new javax.swing.JMenuItem();
        itmRepPasajes = new javax.swing.JMenuItem();
        itmRepAlcohol = new javax.swing.JMenuItem();
        itmRepMedicamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTextoBienvenida.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblTextoBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoBienvenida.setText("Bienvenido a mi Sistema Tìa Juanita!");

        lblImagenAbuelita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abuelita.jpg"))); // NOI18N

        javax.swing.GroupLayout jpnInicioLayout = new javax.swing.GroupLayout(jpnInicio);
        jpnInicio.setLayout(jpnInicioLayout);
        jpnInicioLayout.setHorizontalGroup(
            jpnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addComponent(lblImagenAbuelita, javax.swing.GroupLayout.PREFERRED_SIZE, 638, Short.MAX_VALUE)
        );
        jpnInicioLayout.setVerticalGroup(
            jpnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenAbuelita)
                .addContainerGap())
        );

        itmOperacion.setText("Operaciòn");

        itmOpAgregar.setText("Agregar");

        itmOpAgCigarros.setText("Cigarros");
        itmOpAgCigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpAgCigarrosActionPerformed(evt);
            }
        });
        itmOpAgregar.add(itmOpAgCigarros);

        itmOpAgNarcoticos.setText("Narcoticos");
        itmOpAgregar.add(itmOpAgNarcoticos);

        itmOpAgPasajes.setText("Pasajes");
        itmOpAgregar.add(itmOpAgPasajes);

        itmOpAgAlcohol.setText("Alcohol");
        itmOpAgAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpAgAlcoholActionPerformed(evt);
            }
        });
        itmOpAgregar.add(itmOpAgAlcohol);

        itmOpAgMedicamentos.setText("Medicamentos");
        itmOpAgMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpAgMedicamentosActionPerformed(evt);
            }
        });
        itmOpAgregar.add(itmOpAgMedicamentos);

        itmOperacion.add(itmOpAgregar);

        itmOpEliminar.setText("Eliminar");

        jMenuItem7.setText("Cigarros");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        itmOpEliminar.add(jMenuItem7);

        itmOpElNarcoticos.setText("Narcoticos");
        itmOpEliminar.add(itmOpElNarcoticos);

        itmOpElPasajes.setText("Pasajes");
        itmOpElPasajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpElPasajesActionPerformed(evt);
            }
        });
        itmOpEliminar.add(itmOpElPasajes);

        itmOpElAlcohol.setText("Alcohol");
        itmOpElAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpElAlcoholActionPerformed(evt);
            }
        });
        itmOpEliminar.add(itmOpElAlcohol);

        itmOpElMedicamentos.setText("Medicamentos");
        itmOpEliminar.add(itmOpElMedicamentos);

        itmOperacion.add(itmOpEliminar);

        itmOpEditar.setText("Editar");

        itmOpEdCigarros.setText("Cigarros");
        itmOpEdCigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpEdCigarrosActionPerformed(evt);
            }
        });
        itmOpEditar.add(itmOpEdCigarros);

        itmOpEdNarcoticos.setText("Narcoticos");
        itmOpEditar.add(itmOpEdNarcoticos);

        itmOpEdPasajes.setText("Pasajes");
        itmOpEditar.add(itmOpEdPasajes);

        itmOpEdAlcohol.setText("Alcohol");
        itmOpEdAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpEdAlcoholActionPerformed(evt);
            }
        });
        itmOpEditar.add(itmOpEdAlcohol);

        itmOpEdMedicamentos.setText("Medicamentos");
        itmOpEditar.add(itmOpEdMedicamentos);

        itmOperacion.add(itmOpEditar);

        jMenuBar.add(itmOperacion);

        itmMantenedores.setText("Mantenedores");

        itmManCigarros.setText("Cigarros");
        itmManCigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmManCigarrosActionPerformed(evt);
            }
        });
        itmMantenedores.add(itmManCigarros);

        itmManNarcoticos.setText("Narcoticos");
        itmMantenedores.add(itmManNarcoticos);

        itmManPasajes.setText("Pasajes");
        itmMantenedores.add(itmManPasajes);

        itmManAlcohol.setText("Alcohol");
        itmMantenedores.add(itmManAlcohol);

        itmManMedicamentos.setText("Medicamentos");
        itmManMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmManMedicamentosActionPerformed(evt);
            }
        });
        itmMantenedores.add(itmManMedicamentos);

        jMenuBar.add(itmMantenedores);

        itmReportes.setText("Reportes");

        itmRepCigarros.setText("Cigarros");
        itmRepCigarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRepCigarrosActionPerformed(evt);
            }
        });
        itmReportes.add(itmRepCigarros);

        itmRepNarcoticos.setText("Narcoticos");
        itmReportes.add(itmRepNarcoticos);

        itmRepPasajes.setText("Pasajes");
        itmReportes.add(itmRepPasajes);

        itmRepAlcohol.setText("Alcohol");
        itmReportes.add(itmRepAlcohol);

        itmRepMedicamentos.setText("Medicamentos");
        itmRepMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRepMedicamentosActionPerformed(evt);
            }
        });
        itmReportes.add(itmRepMedicamentos);

        jMenuBar.add(itmReportes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmOpAgCigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpAgCigarrosActionPerformed
        //this.dispose();
        OpAgCigarros panelAgCigarros = new OpAgCigarros();
        Inicio i1 = new Inicio();
        panelAgCigarros.setSize(i1.getSize());
        jpnInicio.removeAll();
        jpnInicio.add(panelAgCigarros);
        jpnInicio.revalidate();
        jpnInicio.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_itmOpAgCigarrosActionPerformed

    private void itmOpAgMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpAgMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmOpAgMedicamentosActionPerformed

    private void itmOpElPasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpElPasajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmOpElPasajesActionPerformed

    private void itmManCigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManCigarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmManCigarrosActionPerformed

    private void itmManMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmManMedicamentosActionPerformed

    private void itmRepMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRepMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmRepMedicamentosActionPerformed

    private void itmRepCigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRepCigarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmRepCigarrosActionPerformed

    private void itmOpAgAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpAgAlcoholActionPerformed

        OpAgAlcohol panelAgAlcohol = new OpAgAlcohol();
        Inicio i1 = new Inicio();
        panelAgAlcohol.setSize(new Inicio().getSize());
        jpnInicio.removeAll();
        jpnInicio.add(panelAgAlcohol);
        jpnInicio.revalidate();
        jpnInicio.repaint();

    }//GEN-LAST:event_itmOpAgAlcoholActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        OpElCigarros panelElCigarros = new OpElCigarros();
        Inicio i1 = new Inicio();
        panelElCigarros.setSize(new Inicio().getSize());
        jpnInicio.removeAll();
        jpnInicio.add(panelElCigarros);
        jpnInicio.revalidate();
        jpnInicio.repaint();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void itmOpElAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpElAlcoholActionPerformed
        OpElAlcohol panelElAlcohol = new OpElAlcohol();
        Inicio i1 = new Inicio();
        panelElAlcohol.setSize(new Inicio().getSize());
        jpnInicio.removeAll();
        jpnInicio.add(panelElAlcohol);
        jpnInicio.revalidate();
        jpnInicio.repaint();

    }//GEN-LAST:event_itmOpElAlcoholActionPerformed

    private void itmOpEdCigarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpEdCigarrosActionPerformed
        OpEdCigarros panelEdCigarros = new OpEdCigarros();
        Inicio i1 = new Inicio();
        panelEdCigarros.setSize(new Inicio().getSize());
        jpnInicio.removeAll();
        jpnInicio.add(panelEdCigarros);
        jpnInicio.revalidate();
        jpnInicio.repaint();

    }//GEN-LAST:event_itmOpEdCigarrosActionPerformed

    private void itmOpEdAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpEdAlcoholActionPerformed
        OpEdAlcohol panelEdAlcohol = new OpEdAlcohol();
        Inicio i1 = new Inicio();
        panelEdAlcohol.setSize(new Inicio().getSize());
        jpnInicio.removeAll();
        jpnInicio.add(panelEdAlcohol);
        jpnInicio.revalidate();
        jpnInicio.repaint();
    }//GEN-LAST:event_itmOpEdAlcoholActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmManAlcohol;
    private javax.swing.JMenuItem itmManCigarros;
    private javax.swing.JMenuItem itmManMedicamentos;
    private javax.swing.JMenuItem itmManNarcoticos;
    private javax.swing.JMenuItem itmManPasajes;
    private javax.swing.JMenu itmMantenedores;
    private javax.swing.JMenuItem itmOpAgAlcohol;
    private javax.swing.JMenuItem itmOpAgCigarros;
    private javax.swing.JMenuItem itmOpAgMedicamentos;
    private javax.swing.JMenuItem itmOpAgNarcoticos;
    private javax.swing.JMenuItem itmOpAgPasajes;
    private javax.swing.JMenu itmOpAgregar;
    private javax.swing.JMenuItem itmOpEdAlcohol;
    private javax.swing.JMenuItem itmOpEdCigarros;
    private javax.swing.JMenuItem itmOpEdMedicamentos;
    private javax.swing.JMenuItem itmOpEdNarcoticos;
    private javax.swing.JMenuItem itmOpEdPasajes;
    private javax.swing.JMenu itmOpEditar;
    private javax.swing.JMenuItem itmOpElAlcohol;
    private javax.swing.JMenuItem itmOpElMedicamentos;
    private javax.swing.JMenuItem itmOpElNarcoticos;
    private javax.swing.JMenuItem itmOpElPasajes;
    private javax.swing.JMenu itmOpEliminar;
    private javax.swing.JMenu itmOperacion;
    private javax.swing.JMenuItem itmRepAlcohol;
    private javax.swing.JMenuItem itmRepCigarros;
    private javax.swing.JMenuItem itmRepMedicamentos;
    private javax.swing.JMenuItem itmRepNarcoticos;
    private javax.swing.JMenuItem itmRepPasajes;
    private javax.swing.JMenu itmReportes;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jpnInicio;
    private javax.swing.JLabel lblImagenAbuelita;
    private javax.swing.JLabel lblTextoBienvenida;
    // End of variables declaration//GEN-END:variables
}
