/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import classes.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class GUIProducto extends javax.swing.JFrame {

    String clase = null;
    Complemento oComplemento;
    Medicamento oMedicamento;
    List<Producto> productos = new ArrayList<Producto>();
    Integer iContadorProductos = 0;

    /**
     * Creates new form GUIProducto
     */
    public GUIProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        rbtMedicamento = new javax.swing.JRadioButton();
        rbtComplemento = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtTipoProducto = new javax.swing.JTextField();
        pnlMedicamento = new javax.swing.JLayeredPane();
        rbtBioEquivalente = new javax.swing.JRadioButton();
        rbtNoBioEquivalente = new javax.swing.JRadioButton();
        txtMedicamentoBioEquivalente = new javax.swing.JTextField();
        pnlComplemento = new javax.swing.JLayeredPane();
        txtCantidadComplemento = new javax.swing.JTextField();
        lblCantidadComplemento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoBuscar = new javax.swing.JTextField();
        btnEliminarProducto = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoBuscarEditar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreEditar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecioEditar = new javax.swing.JTextField();
        btnEditarProducto = new javax.swing.JButton();
        rbtMedicamentoEditar = new javax.swing.JRadioButton();
        rbtComplementoEditar = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        txtTipoProductoEditar = new javax.swing.JTextField();
        btnBuscarProductoEditar = new javax.swing.JButton();
        pnlMedicamentoEditar = new javax.swing.JLayeredPane();
        rbtBioEquivalenteEditar = new javax.swing.JRadioButton();
        rbtNoBioEquivalenteEditar = new javax.swing.JRadioButton();
        txtMedicamentoBioEquivalenteEditar = new javax.swing.JTextField();
        pnlComplementoEditar = new javax.swing.JLayeredPane();
        txtCantidadComplementoEditar = new javax.swing.JTextField();
        lblCantidadComplementoEditar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del producto"));
        jLayeredPane2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel4.setText("Codigo");

        jLabel5.setText(" Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio");

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtMedicamento);
        rbtMedicamento.setText("Medicamento");
        rbtMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtMedicamentoMouseClicked(evt);
            }
        });
        rbtMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMedicamentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtComplemento);
        rbtComplemento.setText("Complemento");
        rbtComplemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtComplementoMouseClicked(evt);
            }
        });
        rbtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtComplementoActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo");

        txtTipoProducto.setEditable(false);
        txtTipoProducto.setText("Medicamento");

        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAgregarProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rbtMedicamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rbtComplemento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtTipoProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtMedicamento)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtComplemento)
                    .addComponent(btnAgregarProducto)
                    .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMedicamento)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnAgregarProducto)
                .addGap(44, 44, 44))
        );

        pnlMedicamento.setBackground(new java.awt.Color(204, 204, 204));
        pnlMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamento"));
        pnlMedicamento.setForeground(new java.awt.Color(153, 153, 153));
        pnlMedicamento.setEnabled(false);

        buttonGroup2.add(rbtBioEquivalente);
        rbtBioEquivalente.setText("Bioequivalente");
        rbtBioEquivalente.setEnabled(false);
        rbtBioEquivalente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtBioEquivalenteMouseClicked(evt);
            }
        });
        rbtBioEquivalente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBioEquivalenteActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtNoBioEquivalente);
        rbtNoBioEquivalente.setText("No BioEquivalente");
        rbtNoBioEquivalente.setEnabled(false);
        rbtNoBioEquivalente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtNoBioEquivalenteMouseClicked(evt);
            }
        });
        rbtNoBioEquivalente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNoBioEquivalenteActionPerformed(evt);
            }
        });

        txtMedicamentoBioEquivalente.setEnabled(false);

        pnlMedicamento.setLayer(rbtBioEquivalente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlMedicamento.setLayer(rbtNoBioEquivalente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlMedicamento.setLayer(txtMedicamentoBioEquivalente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlMedicamentoLayout = new javax.swing.GroupLayout(pnlMedicamento);
        pnlMedicamento.setLayout(pnlMedicamentoLayout);
        pnlMedicamentoLayout.setHorizontalGroup(
            pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                .addGroup(pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicamentoBioEquivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtNoBioEquivalente)
                    .addComponent(rbtBioEquivalente))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        pnlMedicamentoLayout.setVerticalGroup(
            pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                .addComponent(rbtBioEquivalente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtNoBioEquivalente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedicamentoBioEquivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlComplemento.setBackground(new java.awt.Color(204, 204, 204));
        pnlComplemento.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento"));
        pnlComplemento.setForeground(new java.awt.Color(153, 153, 153));
        pnlComplemento.setEnabled(false);

        txtCantidadComplemento.setText("0");
        txtCantidadComplemento.setEnabled(false);

        lblCantidadComplemento.setText("Cantidad");
        lblCantidadComplemento.setEnabled(false);

        pnlComplemento.setLayer(txtCantidadComplemento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlComplemento.setLayer(lblCantidadComplemento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlComplementoLayout = new javax.swing.GroupLayout(pnlComplemento);
        pnlComplemento.setLayout(pnlComplementoLayout);
        pnlComplementoLayout.setHorizontalGroup(
            pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoLayout.createSequentialGroup()
                .addComponent(lblCantidadComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        pnlComplementoLayout.setVerticalGroup(
            pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoLayout.createSequentialGroup()
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidadComplemento)
                    .addComponent(txtCantidadComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMedicamento)
                    .addComponent(jLayeredPane2)
                    .addComponent(pnlComplemento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel3);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Tipo", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(541, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListar)
                .addGap(77, 77, 77))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jLayeredPane3.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del producto"));
        jLayeredPane3.setForeground(new java.awt.Color(153, 153, 153));

        jLabel7.setText("Codigo");

        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtCodigoBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnEliminarProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(799, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        jLayeredPane6.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del producto"));
        jLayeredPane6.setForeground(new java.awt.Color(153, 153, 153));

        jLabel10.setText("Codigo");

        jLabel11.setText(" Nombre");

        txtNombreEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEditarActionPerformed(evt);
            }
        });

        jLabel16.setText("Precio");

        btnEditarProducto.setText("Editar");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtMedicamentoEditar);
        rbtMedicamentoEditar.setText("Medicamento");
        rbtMedicamentoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtMedicamentoEditarMouseClicked(evt);
            }
        });
        rbtMedicamentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMedicamentoEditarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtComplementoEditar);
        rbtComplementoEditar.setText("Complemento");
        rbtComplementoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtComplementoEditarMouseClicked(evt);
            }
        });
        rbtComplementoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtComplementoEditarActionPerformed(evt);
            }
        });

        jLabel17.setText("Tipo");

        txtTipoProductoEditar.setEditable(false);
        txtTipoProductoEditar.setText("Medicamento");

        btnBuscarProductoEditar.setText("Buscar");
        btnBuscarProductoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoEditarActionPerformed(evt);
            }
        });

        jLayeredPane6.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtCodigoBuscarEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtNombreEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtPrecioEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(btnEditarProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(rbtMedicamentoEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(rbtComplementoEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtTipoProductoEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(btnBuscarProductoEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtMedicamentoEditar)
                            .addComponent(txtPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtComplementoEditar)
                            .addComponent(btnEditarProducto)
                            .addComponent(txtTipoProductoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProductoEditar)
                    .addComponent(txtCodigoBuscarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBuscarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProductoEditar)
                .addGap(1, 1, 1)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMedicamentoEditar)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtComplementoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoProductoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnEditarProducto)
                .addGap(15, 15, 15))
        );

        pnlMedicamentoEditar.setBackground(new java.awt.Color(204, 204, 204));
        pnlMedicamentoEditar.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamento"));
        pnlMedicamentoEditar.setForeground(new java.awt.Color(153, 153, 153));
        pnlMedicamentoEditar.setEnabled(false);

        buttonGroup2.add(rbtBioEquivalenteEditar);
        rbtBioEquivalenteEditar.setText("Bioequivalente");
        rbtBioEquivalenteEditar.setEnabled(false);
        rbtBioEquivalenteEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtBioEquivalenteEditarMouseClicked(evt);
            }
        });
        rbtBioEquivalenteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBioEquivalenteEditarActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtNoBioEquivalenteEditar);
        rbtNoBioEquivalenteEditar.setText("No BioEquivalente");
        rbtNoBioEquivalenteEditar.setEnabled(false);
        rbtNoBioEquivalenteEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtNoBioEquivalenteEditarMouseClicked(evt);
            }
        });
        rbtNoBioEquivalenteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNoBioEquivalenteEditarActionPerformed(evt);
            }
        });

        txtMedicamentoBioEquivalenteEditar.setEnabled(false);

        pnlMedicamentoEditar.setLayer(rbtBioEquivalenteEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlMedicamentoEditar.setLayer(rbtNoBioEquivalenteEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlMedicamentoEditar.setLayer(txtMedicamentoBioEquivalenteEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlMedicamentoEditarLayout = new javax.swing.GroupLayout(pnlMedicamentoEditar);
        pnlMedicamentoEditar.setLayout(pnlMedicamentoEditarLayout);
        pnlMedicamentoEditarLayout.setHorizontalGroup(
            pnlMedicamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoEditarLayout.createSequentialGroup()
                .addGroup(pnlMedicamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicamentoBioEquivalenteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtNoBioEquivalenteEditar)
                    .addComponent(rbtBioEquivalenteEditar))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        pnlMedicamentoEditarLayout.setVerticalGroup(
            pnlMedicamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoEditarLayout.createSequentialGroup()
                .addComponent(rbtBioEquivalenteEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtNoBioEquivalenteEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedicamentoBioEquivalenteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlComplementoEditar.setBackground(new java.awt.Color(204, 204, 204));
        pnlComplementoEditar.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento"));
        pnlComplementoEditar.setForeground(new java.awt.Color(153, 153, 153));
        pnlComplementoEditar.setEnabled(false);

        txtCantidadComplementoEditar.setText("0");
        txtCantidadComplementoEditar.setEnabled(false);

        lblCantidadComplementoEditar.setText("Cantidad");
        lblCantidadComplementoEditar.setEnabled(false);

        pnlComplementoEditar.setLayer(txtCantidadComplementoEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlComplementoEditar.setLayer(lblCantidadComplementoEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlComplementoEditarLayout = new javax.swing.GroupLayout(pnlComplementoEditar);
        pnlComplementoEditar.setLayout(pnlComplementoEditarLayout);
        pnlComplementoEditarLayout.setHorizontalGroup(
            pnlComplementoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoEditarLayout.createSequentialGroup()
                .addComponent(lblCantidadComplementoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadComplementoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        pnlComplementoEditarLayout.setVerticalGroup(
            pnlComplementoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoEditarLayout.createSequentialGroup()
                .addGroup(pnlComplementoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidadComplementoEditar)
                    .addComponent(txtCantidadComplementoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMedicamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlComplementoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMedicamentoEditar)
                    .addComponent(jLayeredPane6)
                    .addComponent(pnlComplementoEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed

        System.out.println("Eliminar");

        for (int i = 0; i < productos.size(); i++) {

            //            productos.toString();
            if (productos.get(i).getCodigo() == Integer.parseInt(txtCodigoBuscar.getText())) {
                productos.remove(i);
                iContadorProductos--;
                System.out.println("Eliminado");
            }
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:

        System.out.println("Listar");
        String sDetalle;

        for (int i = 0; i < 10; i++) {
            tblProductos.setValueAt("", i, 0);
            tblProductos.setValueAt("", i, 1);
            tblProductos.setValueAt("", i, 2);
            tblProductos.setValueAt("", i, 3);
            tblProductos.setValueAt("", i, 4);
        }

        System.out.println("productos.toString() " + productos.toString());

        for (int i = 0; i < productos.size(); i++) {

            tblProductos.setValueAt(productos.get(i).getCodigo(), i, 0);
            tblProductos.setValueAt(productos.get(i).getNombre(), i, 1);

            tblProductos.setValueAt(productos.get(i).getPrecio(), i, 2);
            //            int precioConOferta = productos.get(i).getPrecio() - (int) productos.get(i).calcularPrecioOferta();
            //            tblProductos.setValueAt(precioConOferta, i, 2);

            if ((Producto) productos.get(i) instanceof Medicamento) {
                tblProductos.setValueAt("Medicamento", i, 3);
                if (((Medicamento) productos.get(i)).isBioequivalente()) {
                    sDetalle = "Bioequivalente";
                } else {
                    sDetalle = "No Bioequivalente";
                }

                tblProductos.setValueAt(sDetalle, i, 4);
            }
            if ((Producto) productos.get(i) instanceof Complemento) {
                tblProductos.setValueAt("Complemento", i, 3);
                tblProductos.setValueAt(((Complemento) productos.get(i)).getCantidadComponentes(), i, 4);
                //                tblProductos.setValueAt(((Complemento) productos.get(i)).getCantidadComponentes(), i, 4);
            }
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void rbtNoBioEquivalenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNoBioEquivalenteActionPerformed
        txtMedicamentoBioEquivalente.setText("NoBioEquivalente");
    }//GEN-LAST:event_rbtNoBioEquivalenteActionPerformed

    private void rbtNoBioEquivalenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtNoBioEquivalenteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNoBioEquivalenteMouseClicked

    private void rbtBioEquivalenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBioEquivalenteActionPerformed
        txtMedicamentoBioEquivalente.setText("BioEquivalente");
    }//GEN-LAST:event_rbtBioEquivalenteActionPerformed

    private void rbtBioEquivalenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtBioEquivalenteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtBioEquivalenteMouseClicked

    private void rbtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtComplementoActionPerformed
        // TODO add your handling code here:

        lblCantidadComplemento.setEnabled(true);
        txtCantidadComplemento.setEnabled(true);
        pnlComplemento.setEnabled(true);

        pnlMedicamento.setEnabled(false);
        rbtBioEquivalente.setEnabled(false);
        rbtNoBioEquivalente.setEnabled(false);
        txtMedicamentoBioEquivalente.setEnabled(false);
    }//GEN-LAST:event_rbtComplementoActionPerformed

    private void rbtComplementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtComplementoMouseClicked
        txtTipoProducto.setText("Complemento");
    }//GEN-LAST:event_rbtComplementoMouseClicked

    private void rbtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMedicamentoActionPerformed
        // TODO add your handling code here:

        lblCantidadComplemento.setEnabled(false);
        txtCantidadComplemento.setEnabled(false);
        pnlComplemento.setEnabled(false);

        pnlMedicamento.setEnabled(true);
        rbtBioEquivalente.setEnabled(true);
        rbtNoBioEquivalente.setEnabled(true);
        txtMedicamentoBioEquivalente.setEnabled(true);
    }//GEN-LAST:event_rbtMedicamentoActionPerformed

    private void rbtMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtMedicamentoMouseClicked
        txtTipoProducto.setText("Medicamento");
    }//GEN-LAST:event_rbtMedicamentoMouseClicked

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:

        System.out.println("Agregar");

        //El código de producto debe ser un número entre 1000 y 9999
        try {
            if (Integer.parseInt(this.txtCodigo.getText()) < 1000
                    && Integer.parseInt(this.txtCodigo.getText()) > 9999) {
                System.out.println("El código de producto debe ser un número entre 1000 y 9999.");
                JOptionPane.showMessageDialog(
                        null,
                        "El código de producto debe ser un número entre 1000 y 9999.",
                        "AVISO DE SISTEMA",
                        JOptionPane.PLAIN_MESSAGE
                );
            }
        } catch (Exception e) {
            System.out.println("Mensaje " + e.getMessage());;
        }
        //El nombre del producto debe tener más de 2 caracteres
        try {
            if (this.txtNombre.getText().length() < 2) {
                System.out.println("El nombre del producto debe tener más de 2 caracteres.");

                JOptionPane.showMessageDialog(
                        null,
                        "El nombre del producto debe tener más de 2 caracteres.",
                        "AVISO DE SISTEMA",
                        JOptionPane.PLAIN_MESSAGE
                );
            }
        } catch (Exception e) {
            System.out.println("Mensaje " + e.getMessage());;
        }
        //El precio del producto debe ser mayor a 0
        try {
            if (Integer.parseInt(this.txtPrecio.getText()) <= 0) {
                System.out.println("El precio del producto debe ser mayor a 0.");
                JOptionPane.showMessageDialog(
                        null,
                        "El precio del producto debe ser mayor a 0.",
                        "AVISO DE SISTEMA",
                        JOptionPane.PLAIN_MESSAGE
                );
            }
        } catch (Exception e) {
            System.out.println("Mensaje " + e.getMessage());;
        }

        if (txtTipoProducto.getText().equals("Medicamento")) {

            boolean bMedicamentoBioEquivalente = false;
            if (txtMedicamentoBioEquivalente.getText().equals("BioEquivalente")) {
                bMedicamentoBioEquivalente = true;
            }
            Medicamento oMedicamento = new Medicamento(
                    Integer.parseInt(this.txtCodigo.getText()) // CODIGO
                    ,
                     txtNombre.getText() // NOMBRE
                    ,
                     Integer.parseInt(txtPrecio.getText()) // PRECIO
                    ,
                     bMedicamentoBioEquivalente // BIOEQUIVALENTE
            );

            // Si el producto es bioequivalente, se le aplica al precio el descuento correspondiente
            if (bMedicamentoBioEquivalente) {
                oMedicamento.setPrecio(oMedicamento.getPrecio() - (int) oMedicamento.calcularPrecioOferta());
            }
            productos.add(iContadorProductos, oMedicamento);
            iContadorProductos++;
            System.out.println("Medicamento Agregado");
        }

        if (txtTipoProducto.getText().equals("Complemento")) {

            //La cantidad de componentes debe ser mayor a 0
            try {
                if (Integer.parseInt(this.txtCantidadComplemento.getText()) <= 0) {
                    System.out.println("La cantidad de componentes debe ser mayor a 0.");
                    JOptionPane.showMessageDialog(
                            null,
                            "La cantidad de componentes debe ser mayor a 0.",
                            "AVISO DE SISTEMA",
                            JOptionPane.PLAIN_MESSAGE
                    );
                }
            } catch (Exception e) {
                System.out.println("Mensaje " + e.getMessage());;
            }

            int txtCantidadComplemento = 0;

            Complemento oComplemento = new Complemento(
                    Integer.parseInt(this.txtCodigo.getText()) // CODIGO
                    ,
                     this.txtNombre.getText() // NOMBRE
                    ,
                     Integer.parseInt(this.txtPrecio.getText()) // PRECIO
                    ,
                     Integer.parseInt(this.txtCantidadComplemento.getText()) // CANTIDAD COMPLEMENTO
            );

            // Si la cantidad de componentes del producto es menor a 5, se aplica al precio el descuento correspondiente.
            if (oComplemento.getCantidadComponentes() < 5) {
                oComplemento.setPrecio(
                        oComplemento.getPrecio() - (int) oComplemento.calcularPrecioOferta()
                );
            }
            productos.add(iContadorProductos, oComplemento);
            iContadorProductos++;
            System.out.println("Complemento Agregado");
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEditarActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        // TODO add your handling code here:

        System.out.println("Editar");
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void rbtMedicamentoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtMedicamentoEditarMouseClicked
        // TODO add your handling code here:
        txtTipoProductoEditar.setText("Medicamento");
    }//GEN-LAST:event_rbtMedicamentoEditarMouseClicked

    private void rbtMedicamentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMedicamentoEditarActionPerformed
        // TODO add your handling code here:

        lblCantidadComplementoEditar.setEnabled(false);
        txtCantidadComplementoEditar.setEnabled(false);
        pnlComplementoEditar.setEnabled(false);

        pnlMedicamentoEditar.setEnabled(true);
        rbtBioEquivalenteEditar.setEnabled(true);
        rbtNoBioEquivalenteEditar.setEnabled(true);
        txtMedicamentoBioEquivalenteEditar.setEnabled(true);

    }//GEN-LAST:event_rbtMedicamentoEditarActionPerformed

    private void rbtComplementoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtComplementoEditarMouseClicked
        // TODO add your handling code here:
        txtTipoProductoEditar.setText("Complemento");


    }//GEN-LAST:event_rbtComplementoEditarMouseClicked

    private void rbtComplementoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtComplementoEditarActionPerformed
        // TODO add your handling code here:

        lblCantidadComplementoEditar.setEnabled(true);
        txtCantidadComplementoEditar.setEnabled(true);
        pnlComplementoEditar.setEnabled(true);

        pnlMedicamentoEditar.setEnabled(false);
        rbtBioEquivalenteEditar.setEnabled(false);
        rbtNoBioEquivalenteEditar.setEnabled(false);
        txtMedicamentoBioEquivalenteEditar.setEnabled(false);

    }//GEN-LAST:event_rbtComplementoEditarActionPerformed

    private void rbtBioEquivalenteEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtBioEquivalenteEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtBioEquivalenteEditarMouseClicked

    private void rbtBioEquivalenteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBioEquivalenteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtBioEquivalenteEditarActionPerformed

    private void rbtNoBioEquivalenteEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtNoBioEquivalenteEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNoBioEquivalenteEditarMouseClicked

    private void rbtNoBioEquivalenteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNoBioEquivalenteEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNoBioEquivalenteEditarActionPerformed

    private void btnBuscarProductoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoEditarActionPerformed
        // TODO add your handling code here:

        System.out.println("BuscarProductoEditar");

        for (int i = 0; i < productos.size(); i++) {
            if (productos.get(i).getCodigo() == Integer.parseInt(txtCodigoBuscarEditar.getText())) {
                System.out.println("Encontrado para editar");

                txtNombreEditar.setText(
                        productos.get(i).getNombre()
                );
                txtPrecioEditar.setText(
                        productos.get(i).getPrecio() + ""
                );

                if ((Producto) productos.get(i) instanceof Complemento) {

                    lblCantidadComplementoEditar.setEnabled(true);
                    txtCantidadComplementoEditar.setEnabled(true);
                    pnlComplementoEditar.setEnabled(true);

                    pnlMedicamentoEditar.setEnabled(false);
                    rbtBioEquivalenteEditar.setEnabled(false);
                    rbtNoBioEquivalenteEditar.setEnabled(false);
                    txtMedicamentoBioEquivalenteEditar.setEnabled(false);

                    rbtMedicamentoEditar.setSelected(false);
                    rbtComplementoEditar.setSelected(true);
                    txtCantidadComplementoEditar.setText(
                            ((Complemento) productos.get(i)).getCantidadComponentes() + ""
                    );
                    txtTipoProductoEditar.setText(
                            "Complemento"
                    );
                }
                if ((Producto) productos.get(i) instanceof Medicamento) {

                    lblCantidadComplementoEditar.setEnabled(false);
                    txtCantidadComplementoEditar.setEnabled(false);
                    pnlComplementoEditar.setEnabled(false);

                    pnlMedicamentoEditar.setEnabled(true);
                    rbtBioEquivalenteEditar.setEnabled(true);
                    rbtNoBioEquivalenteEditar.setEnabled(true);
                    txtMedicamentoBioEquivalenteEditar.setEnabled(true);

                    rbtMedicamentoEditar.setSelected(true);
                    rbtComplementoEditar.setSelected(false);
                    if (((Medicamento) productos.get(i)).isBioequivalente()) {
                        txtMedicamentoBioEquivalenteEditar.setText("Bioequivalente");
                        rbtBioEquivalenteEditar.setSelected(true);
                        rbtNoBioEquivalenteEditar.setSelected(false);
                    } else {
                        txtMedicamentoBioEquivalenteEditar.setText("No Bioequivalente");
                        rbtBioEquivalenteEditar.setSelected(false);
                        rbtNoBioEquivalenteEditar.setSelected(true);
                    }

                    txtTipoProductoEditar.setText(
                            "Medicamento"
                    );
                }

            }
        }

    }//GEN-LAST:event_btnBuscarProductoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIProducto().setVisible(true);
//                new GUIProducto().pnlComplemento.setVisible(false);
//                new GUIProducto().pnlMedicamento.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarProducto1;
    private javax.swing.JButton btnBuscarProductoEditar;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCantidadComplemento;
    private javax.swing.JLabel lblCantidadComplementoEditar;
    private javax.swing.JLayeredPane pnlComplemento;
    private javax.swing.JLayeredPane pnlComplementoEditar;
    private javax.swing.JLayeredPane pnlMedicamento;
    private javax.swing.JLayeredPane pnlMedicamentoEditar;
    private javax.swing.JRadioButton rbtBioEquivalente;
    private javax.swing.JRadioButton rbtBioEquivalenteEditar;
    private javax.swing.JRadioButton rbtComplemento;
    private javax.swing.JRadioButton rbtComplementoEditar;
    private javax.swing.JRadioButton rbtMedicamento;
    private javax.swing.JRadioButton rbtMedicamentoEditar;
    private javax.swing.JRadioButton rbtNoBioEquivalente;
    private javax.swing.JRadioButton rbtNoBioEquivalenteEditar;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidadComplemento;
    private javax.swing.JTextField txtCantidadComplementoEditar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoBuscar;
    private javax.swing.JTextField txtCodigoBuscar1;
    private javax.swing.JTextField txtCodigoBuscarEditar;
    private javax.swing.JTextField txtMedicamentoBioEquivalente;
    private javax.swing.JTextField txtMedicamentoBioEquivalenteEditar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEditar;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioEditar;
    private javax.swing.JTextField txtTipoProducto;
    private javax.swing.JTextField txtTipoProductoEditar;
    // End of variables declaration//GEN-END:variables
}
