package view.Pelicula;

import controller.PeliculaController;
import model.Pelicula;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtPeliculaCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtPeliculaPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtPeliculaNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRBtnPeliculaFormato4k = new javax.swing.JRadioButton();
        jCmbPeliculaCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButtonPeliculaAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxtPeliculaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPeliculaCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Agregar Película");

        jLabel2.setText("Código");

        jLabel4.setText("Nombre");

        jTxtPeliculaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPeliculaPrecioActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio");

        jTxtPeliculaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPeliculaNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Formato 4k");

        jRBtnPeliculaFormato4k.setText("Si");
        jRBtnPeliculaFormato4k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnPeliculaFormato4kActionPerformed(evt);
            }
        });

        jCmbPeliculaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Fantasía", "Terror", "Infantil" }));

        jLabel7.setText("Categoria");

        jButtonPeliculaAgregar.setText("Agregar");
        jButtonPeliculaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeliculaAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPeliculaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPeliculaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPeliculaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbPeliculaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtnPeliculaFormato4k)
                            .addComponent(jButtonPeliculaAgregar))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtPeliculaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPeliculaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPeliculaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnPeliculaFormato4k)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbPeliculaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPeliculaAgregar)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPeliculaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPeliculaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPeliculaCodigoActionPerformed

    private void jTxtPeliculaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPeliculaPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPeliculaPrecioActionPerformed

    private void jTxtPeliculaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPeliculaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPeliculaNombreActionPerformed

    private void jRBtnPeliculaFormato4kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnPeliculaFormato4kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtnPeliculaFormato4kActionPerformed

    private void jButtonPeliculaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeliculaAgregarActionPerformed
        int codigoPelicula = 0;
        int precioPelicula = 0;
        int id_categoriaPelicula = 1;
        String formato4kPelicula;
        String nombrePelicula;

        // codigo
        try {
            codigoPelicula = Integer.parseInt(jTxtPeliculaCodigo.getText());
            if (codigoPelicula < 10000 || codigoPelicula > 99999) {
                JOptionPane.showMessageDialog(this, "El código de la pelicula debe ser entre 10000 y 99999", "Advertencia", JOptionPane.WARNING_MESSAGE);
                jTxtPeliculaCodigo.requestFocus();
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código de la pelicula  debe ser un número", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jTxtPeliculaCodigo.requestFocus();
        }

        //nombre
        nombrePelicula = jTxtPeliculaNombre.getText();
        if (nombrePelicula.length() < 3) {
            JOptionPane.showMessageDialog(this, "El nombre de la pelicula debe ser de mínimo 3 caracteres de largo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jTxtPeliculaNombre.requestFocus();
        } else if (nombrePelicula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la pelicula no puede estar en blanco", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jTxtPeliculaNombre.requestFocus();
        }

        // precio
        try {
            precioPelicula = Integer.parseInt(jTxtPeliculaPrecio.getText());
            if (precioPelicula <= 1000) {
                JOptionPane.showMessageDialog(this, "El precio de la película debe ser mayor a 1000", "Advertencia", JOptionPane.WARNING_MESSAGE);
                jTxtPeliculaPrecio.requestFocus();
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio de la pelicula  debe ser un número", "Advertencia", JOptionPane.WARNING_MESSAGE);
            jTxtPeliculaPrecio.requestFocus();
        }

        // formato 4k
        if (jRBtnPeliculaFormato4k.isSelected()) {
            formato4kPelicula = "S";
        } else {
            formato4kPelicula = "N";
        }

        Pelicula pelicula = new Pelicula(codigoPelicula, precioPelicula, id_categoriaPelicula, formato4kPelicula, nombrePelicula);
        PeliculaController PeliculaController = new PeliculaController();

        // cuando se descomenta  y no existe error se pega el programa
//        if (PeliculaController.buscarPeliculaPorCodigo(codigoPelicula).getCodigo() != 0) {
//            JOptionPane.showMessageDialog(this, "Existe un error al agregar la película. \n El código de la película ya existe", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }

        if (PeliculaController.agregarPelicula(pelicula)) {
            JOptionPane.showMessageDialog(this, "Su pelicula: " + nombrePelicula + " se ha agregado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Existe un error al agregar la película", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPeliculaAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPeliculaAgregar;
    private javax.swing.JComboBox<String> jCmbPeliculaCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRBtnPeliculaFormato4k;
    private javax.swing.JTextField jTxtPeliculaCodigo;
    private javax.swing.JTextField jTxtPeliculaNombre;
    private javax.swing.JTextField jTxtPeliculaPrecio;
    // End of variables declaration//GEN-END:variables
}
