/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Operacion.Editar;

import Modelo.Alcohol;
import static ventas.Ventas.arrayAlcohol;

public class OpEdAlcohol extends javax.swing.JPanel {

    int varSeleccion = 0;

    public OpEdAlcohol() {
        initComponents();
        //JOptionPane.showMessageDialog(this, ui,"", WIDTH);
        lstAlcohol.setModel(
                Modelo.Alcohol.getListado(arrayAlcohol)
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAlcohol = new javax.swing.JList<>();
        btnEditarCigarro = new javax.swing.JButton();
        txtValorProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtDistribucion = new javax.swing.JTextField();
        txtDesProducto = new javax.swing.JTextField();
        txtGradoAlcohol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        lstAlcohol.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAlcohol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAlcoholMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstAlcohol);

        btnEditarCigarro.setText("Editar Alcohol");
        btnEditarCigarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCigarroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("EDITAR ALCOHOL DE LA LISTA");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Valor Producto");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Distribucion");

        jLabel6.setText("Grados Alcoholicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditarCigarro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGradoAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtValorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(28, 28, 28))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGradoAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarCigarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCigarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCigarroActionPerformed

        boolean validarDatos = Controller.AlcoholController.validarDatos(
                txtDesProducto,
                txtCantidad,
                txtValorProducto,
                txtDistribucion,
                txtGradoAlcohol
        );

        if (validarDatos) {
            System.out.println("Se puede editar");
            arrayAlcohol.get(varSeleccion).setDescripcionProductos(txtDesProducto.getText());
            arrayAlcohol.get(varSeleccion).setValorProducto(Integer.valueOf(txtValorProducto.getText()));
            arrayAlcohol.get(varSeleccion).setCantidad(Integer.valueOf(txtCantidad.getText()));
//            arrayAlcohol.get(varSeleccion).setDistribucion(
//                    Integer.valueOf(
//                            txtDistribucion.getText()
//                    )
//            );
            arrayAlcohol.get(varSeleccion).setGradoAlcohol(Double.valueOf(txtGradoAlcohol.getText()));

            lstAlcohol.setModel(Modelo.Alcohol.getListado(arrayAlcohol));
        } else {
            System.out.println("NO se puede editar");
        }

    }//GEN-LAST:event_btnEditarCigarroActionPerformed

    private void lstAlcoholMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAlcoholMouseClicked
        varSeleccion = lstAlcohol.getSelectedIndex();
        txtDesProducto.setText(arrayAlcohol.get(lstAlcohol.getSelectedIndex()).getDescripcionProductos());
        txtValorProducto.setText(String.valueOf(arrayAlcohol.get(lstAlcohol.getSelectedIndex()).getValorProducto()));
        txtCantidad.setText(String.valueOf(arrayAlcohol.get(lstAlcohol.getSelectedIndex()).getCantidad()));
        txtDistribucion.setText(arrayAlcohol.get(lstAlcohol.getSelectedIndex()).getDistribucion());
        txtGradoAlcohol.setText(String.valueOf(arrayAlcohol.get(lstAlcohol.getSelectedIndex()).getGradoAlcohol()));
    }//GEN-LAST:event_lstAlcoholMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCigarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAlcohol;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDesProducto;
    private javax.swing.JTextField txtDistribucion;
    private javax.swing.JTextField txtGradoAlcohol;
    private javax.swing.JTextField txtValorProducto;
    // End of variables declaration//GEN-END:variables
}
